name: Ubuntu build

on: [push, pull_request]

jobs:
# Ref.:
#   https://gitlab.com/nvidia/container-images/cuda/-/blob/master/dist/ubuntu18.04/10.1/base/Dockerfile
#   https://github.com/ComputationalRadiationPhysics/picongpu/blob/0.5.0/share/picongpu/dockerfiles/ubuntu-1604/Dockerfile
#   https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/
  build_gcc_nvcc:
    name: NVCC 11.0.2 SP [Linux]
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        .github/workflows/dependencies/nvcc11.sh
    - name: Build
      run: |
        export PATH=/usr/local/nvidia/bin:/usr/local/cuda/bin:${PATH}
        export LD_LIBRARY_PATH=/usr/local/nvidia/lib:/usr/local/nvidia/lib64:/usr/local/cuda/lib64:${LD_LIBRARY_PATH}
        which nvcc || echo "nvcc not in PATH!"

        export CXXFLAGS="-Wall -Wextra -Werror"

        cmake -S . -B build                   \
          -DCMAKE_CUDA_ARCHITECTURES=35       \
          -DSAME_NVCC_FLAGS_IN_SUBPROJECTS=ON
        cmake --build build -j 2
        sudo cmake --build build --target install

